require 'json'
require 'base64'
require 'openssl'
require 'namae'
require 'logger'
require 'sinatra/base'
require 'redis'
require 'resque/server'
require 'desk_api'
require 'platform-api'
require 'active_model'
require 'active_support'
require 'active_support/core_ext/hash'
require 'active_support/inflector'
require 'securerandom'
require 'require_all'
require_all './{adapters,helpers,controllers,jobs}/**/*.rb'
$app = ApplicationController.new